Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
  MaxHeaderBytes: 1048576 # 1MB
App:
  DefaultPageSize: 10
  MaxPageSize: 100
Log:
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  LogMaxSize: 600 # 600MB
  LogMaxAge: 10 # 10天
  LogLocalTime: true
Database:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: # 填写你的数据库密码
  Host: 127.0.0.1:3306
  DBName: hello_blog
  TablePrefix: blog_
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30